system:
  mode: standalone  # standalone / connected
  camera_id: 0
  
display:
  width: 1280
  height: 720

ai:
  model_path: 'models/seg_best_process.pt'
  db_path: 'database/pill_fingerprints.pkl'
  conf_threshold: 0.5

endpoints:
  his_api: 'http://localhost:8000/api'
