system:
  mode: standalone

display:
  width: 1280
  height: 720

artifacts:
  model: 'models/seg_best_process.pt'          # <-- ต้องตรงกับ SyncManager
  pack_vec: 'database/pill_fingerprints.pkl'   # <-- Key นี้ต้องมี
  drug_list: 'database/drug_list.json'

settings:
  yolo_conf: 0.5